spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/sijak
      username: root
      password: a123456789
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true